language: go

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - docker build . --build-arg version="v0.0.1" --build-arg ${TRAVIS_COMMIT} -t sgrzebieta/api-test:latest
  - docker tag sgrzebieta/api-test:latest sgrzebieta/api-test:${TRAVIS_BUILD_ID}.${TRAVIS_BUILD_NUMBER}